### ISSUE TITLE
package-lock.json points to garmin.com

### ISSUE THREAD

**Issue by deobald** [jdhillen/vue-template#31]
Hey there! I was following your Vue + Electron tutorial from the talk you gave here:

https://www.youtube.com/watch?v=qiXWFHMFb7A

...and `npm install` in your template is failing because it's trying to grab packages from [mirrors.garmin.com](https://mirrors.garmin.com/), which fails DNS lookups for me (and I'm guessing most of the world... this is probably an internal domain?)

See https://github.com/jdhillen/vue-template/blob/3854c7cce8f5cf45b49bd0308d2fe690b4518c29/package-lock.json#L560

HTH.

**Comment by jdhillen** [comment]
Looks like a package.lock issue. I'll get that updated.

**Comment by jdhillen** [comment]
A new release has resolved the issues - https://github.com/jdhillen/vue-template/releases/tag/1.3.4
